kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: skillpulse-ns

type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz
  DB_PASSWORD: c2tpbGxwdWxzZTEyMw==
  MYSQL_PASSWORD: c2tpbGxwdWxzZTEyMw==
